[package]
name = "sarme"
description = "A self-hostable lyrics downloader for your music library."
authors = ["Kamil Pomykała <kamil@kamilpomykala.dev>"]
version = "0.1.0"
edition = "2024"

[lints.clippy]
pedantic = { level = "deny", priority = -1 }
# PANIC SAFETY
unwrap_used = "deny"
expect_used = "deny"
indexing_slicing = "deny"
unimplemented = "deny"
unchecked_time_subtraction = "deny"
todo = "deny"
string_slice = "deny"
panic_in_result_fn = "deny"
panic = "deny"
# OTHER
large_enum_variant = "deny"

[dependencies]
dotenvy = "0.15"
thiserror = "2"

#
# Database
#
sqlx = { version = "0.9", default-features = false, features = ["runtime-tokio", "sqlite", "migrate", "macros"] }

#
# Web
#
axum = "0.8"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tower-http = { version = "0.7", features = ["trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
listenfd = "1"

#
# HTMX and Templating
#
askama = "0.16"

[dev-dependencies]
tempfile = "3"
